FROM jupyter/scipy-notebook

USER root
RUN apt-get update && apt-get install -y curl

# Start Nodejs kernal

## Removing the packaged nodejs in favor of our own controlled version
## The base notebook includes this for jupyter hub which we are not using.
RUN conda uninstall nodejs -y
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash && \
	apt-get install -y nodejs g++ make software-properties-common libzmq3-dev

RUN mkdir -p /tmp/kernals/jupyter-nodejs
COPY ./jupyter-nodejs /tmp/kernals/jupyter-nodejs
RUN chown -R $NB_USER /tmp/kernals/jupyter-nodejs

USER $NB_USER
WORKDIR /tmp/kernals/jupyter-nodejs
RUN mkdir -p $HOME/.ipython/kernels/nodejs/
RUN mkdir -p $HOME/.local/share/jupyter/kernals
RUN npm install && node install.js
RUN npm run build
RUN npm run build-ext
WORKDIR /tmp/kernals/jupyter-nodejs/node_modules/zmq/
RUN npm run install
RUN cp -R $HOME/.ipython/kernels/nodejs/ $HOME/.local/share/jupyter/kernals

# End Nodejs kernal

# Start PHP kernal
USER root
RUN apt-get install -y \
	php7.0-cli \
	php-zmq
RUN curl -sL https://getcomposer.org/installer | php && \
	mv composer.phar /usr/local/bin/composer
RUN curl -sL https://litipk.github.io/Jupyter-PHP-Installer/dist/jupyter-php-installer.phar > /tmp/jupyter-php.phar
RUN php /tmp/jupyter-php.phar install

# End PHP kernal

USER $NB_USER
WORKDIR $HOME

EXPOSE 8888
